#!/bin/bash
#SBATCH --job-name=UNET_cityscapes
#SBATCH --output=slurm_%j.out
#SBATCH --error=slurm_%j.err
#SBATCH --account=pgs0404
#SBATCH --partition=batch
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=32G
#SBATCH --gres=gpu:a100:1
#SBATCH --time=10:00:00

PYTHON=/Desktop/anaconda3/bin/python
PIP=/Desktop/anaconda3/bin/pip

$PIP install timm albumentations tqdm

cd /Desktop/CityScapeSegmentation

$PYTHON train.py \
    --model UNet \
    --batch_size 16 \
    --epochs 300 \
    --cityscape_path /Desktop/CityScapeSegmentation/Data_30k \
    --rs_dir /Desktop/CityScapeSegmentation/trained_results_30K/UNet_results
